version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.9
  build:
    commands:
      - find template.yml
      - aws cloudformation package --template-file template.yml --s3-bucket codepipeline-eu-west-2-248832724193 --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml