AWSTemplateFormatVersion: 2010-09-09
Description: Server for the Incandescent app
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    PermissionsBoundary:
      Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary
Parameters:
  AppId:
    Type: String
Resources:
  IncandescentLambdaBasicExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  PythonRestClientLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1uhmeo0ymx86b/0badb5fa9fa1b90c781a1278f393d621
      CompatibleRuntimes:
      - python3.9
  SendOperationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1uhmeo0ymx86b/55971da7d961089df254ed5a238e5f2b
      Handler: send-operation.lambda_handler
      Runtime: python3.9
      Layers:
      - Ref: PythonRestClientLambdaLayer
      Role:
        Fn::GetAtt:
        - IncandescentLambdaBasicExecutionRole
        - Arn
      Events:
        SendOperation:
          Type: Api
          Properties:
            Path: /devices/{device}/operations
            Method: patch
Outputs:
  ServerApi:
    Description: URL for the server API
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com
